services:
  hivewatcher:
    image: brianoflondon/podping-hivepinger:latest
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    container_name: hivewatcher
    command: ["python", "src/hivewatcher/watch.py", "--no-all-pings", "--podping-prefix", "pp", "--call-url", "http://hivepinger:8000/"]
    restart: unless-stopped
    networks:
      - hivepinger-network
    volumes:
      - ./data:/hivepinger/data

  all-pings-watcher:
    image: brianoflondon/podping-hivepinger:latest
    container_name: all-pings-watcher
    command: ["python", "src/hivewatcher/watch.py", "--all-pings", "--no-threespeak", "--podping-prefix", "pp", "--call-url", "http://hivepinger:8000/"]
    restart: unless-stopped
    networks:
      - hivepinger-network
    volumes:
      - ./data/all-pings:/hivepinger/data

networks:
  hivepinger-network:
    external: true
    name: gossip_hivepinger-network
