services:
  hivewatcher:
    image: brianoflondon/podping-hivepinger:pr-36
    container_name: hivewatcher
    command: ["python", "src/hivewatcher/watch.py", "--no-all-pings", "--podping-prefix", "pp", "--call-url", "http://hivepinger:8000/"]
    restart: unless-stopped
    networks:
      - hivepinger-network
    volumes:
      - ./data:/app/data

networks:
  hivepinger-network:
    external:
      name: gossip_hivepinger-network
